---
language: ruby

rvm:
- 2.0.0
- 2.1.5
- 2.2.0

script:
- cd service_management/azure && bundle exec rake test:unit
- cd ../../resource_management && bundle install && rake spec
- if [ "$TRAVIS_SECURE_ENV_VARS" == "true" ] ; then rake test:integration ; fi

